/**
 * Presentation export (roadmap brief s9 item 16: "a sample presentation
 * generated from the same source content").
 *
 * This is the vertical-slice **proof**, not the Phase 9 tool. It demonstrates
 * that one approved record can drive both the lesson and a deck. Deliberately
 * absent, because the brief defers them: audience selection, length and depth
 * controls, event-type templates, theming, and any user interface.
 *
 * The one rule that matters: this builder **never rewrites content**. Every
 * learner-facing sentence in the output is a field from the record, copied
 * verbatim. Summarizing here would create a second, unreviewed version of the
 * company's explanation, which is exactly what the canonical-record system
 * exists to prevent.
 */

export interface DeckExample {
  text: string;
  clue: string;
}

export interface DeckRecord {
  key: string;
  title: string;
  definition: string;
  presentationSummary: string;
  speakerNotes: string;
  examples: DeckExample[];
  sources: string[];
}

export interface DeckOptions {
  /** Deck title. Chosen by the operator; the only free text in the output. */
  title: string;
  /** Published content version the records came from, for traceability. */
  contentVersion: number;
  /** ISO date stamped on the deck. Passed in so output is reproducible. */
  generatedOn: string;
}

function slide(lines: string[]): string {
  return lines.filter((line) => line !== null && line !== undefined).join("\n");
}

/**
 * Renders Markdown with `---` slide separators, which Marp, Deckset and Google
 * Slides importers all understand. No dependency, and it stays reviewable in a
 * pull request, which a binary deck would not.
 */
export function buildDeck(records: DeckRecord[], options: DeckOptions): string {
  const slides: string[] = [];

  slides.push(
    slide([
      `# ${options.title}`,
      "",
      `Generated from approved canonical records, content version ${options.contentVersion}.`,
      "",
      `Every definition and summary below is the approved wording, copied without change. Do not edit this file: edit the record and regenerate, or the deck and the product will disagree.`,
      "",
      `Generated ${options.generatedOn}.`,
    ]),
  );

  for (const record of records) {
    const lines = [
      `## ${record.title}`,
      "",
      `**${record.definition}**`,
      "",
      record.presentationSummary,
    ];

    if (record.examples.length > 0) {
      lines.push("", "### Examples", "");
      for (const example of record.examples) {
        lines.push(`- ${example.text} (${example.clue})`);
      }
    }

    if (record.sources.length > 0) {
      lines.push("", "### References", "");
      for (const source of record.sources) lines.push(`- ${source}`);
    }

    lines.push("", "> **Speaker notes.** " + record.speakerNotes);
    slides.push(slide(lines));
  }

  slides.push(
    slide([
      "## Provenance",
      "",
      `Content version ${options.contentVersion}. Records used:`,
      "",
      ...records.map((record) => `- \`${record.key}\``),
      "",
      "Regenerate with `npm run content:deck` after any record change.",
    ]),
  );

  return `${slides.join("\n\n---\n\n")}\n`;
}
